Reland "siso: refactor hashfs SetState"
This reverts commit 9470236b7870947345c2791a5c9ff6b52b507407.

Reason for revert:
hfs.initial may become nil, if goroutine in SetState finishes
early before hfs.initial.info() is called.

Actually, we don't need to have *initialEntryStates as member
of *HashFS.
Make it local variable instead.

Original change's description:
> Revert "siso: refactor hashfs SetState"
>
> This reverts commit 3659ea5e386211c40f006805623eae22024e9fe5.
>
> Reason for revert:
> https://ci.chromium.org/ui/p/infra/builders/try/buildinfra-try-linux/b8696639916852113905/overview
> ```
> === RUN   TestBuild_ValidationsNested
>     /b/s/w/ir/cache/builder/build/siso/subcmd/ninja/e2e_validations_test.go:208: -- first build
> --- FAIL: TestBuild_ValidationsNested (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xbb9f1a]
>
> goroutine 426 [running]:
> testing.tRunner.func1.2({0x106e140, 0x1ceea00})
> 	/b/s/w/ir/cache/go1_24_10/src/testing/testing.go:1734 +0x21c
> testing.tRunner.func1()
> 	/b/s/w/ir/cache/go1_24_10/src/testing/testing.go:1737 +0x35e
> panic({0x106e140?, 0x1ceea00?})
> 	/b/s/w/ir/cache/go1_24_10/src/runtime/panic.go:792 +0x132
> go.chromium.org/build/siso/hashfs.(*initialEntryStates).info(0xc000674a80?)
> 	/b/s/w/ir/cache/builder/build/siso/hashfs/state.go:700 +0x1a
> go.chromium.org/build/siso/hashfs.(*HashFS).SetState(0xc0003cfc20, {0x141b168, 0xc000f4b810}, 0xc000440cf0)
> 	/b/s/w/ir/cache/builder/build/siso/hashfs/state.go:799 +0xaa8
> go.chromium.org/build/siso/hashfs.New({0x141b168, 0xc000f4b810}, {{0x126344d, 0xe}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
> ```
>
> Original change's description:
> > siso: refactor hashfs SetState
> >
> > This CL refactors the SetState function in siso/hashfs/state.go.
> >
> > The main change is the introduction of a new initialEntryStates.
> > The logic for processing entries from the .siso_fs_state file,
> > comparing them with the local filesystem, and updating the in-memory
> > state has been moved out of the monolithic SetState function and
> > into methods on this new struct.
> >
> > As a result, SetState is now much shorter and acts as an
> > orchestrator, delegating the steps of state initialization
> > (preparing, updating from disk, storing entries) to the initialEntryStates helper.
> >
> > Additionally, the clog package was modified to allow a logger to
> > have an io.Writer. This is used in SetState to provide more detailed
> > logging during the state initialization process.
> >
> > Change-Id: I8a90e45446a7b25581682434010098ae1ee9e838
> > Reviewed-on: https://chromium-review.googlesource.com/c/build/+/7207899
> > Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> > Commit-Queue: Fumitoshi Ukai <ukai@google.com>
> > Reviewed-by: Junji Watanabe <jwata@google.com>
>
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: If993b118c6a4bc84e8c2b3c58ee0b935e542b69c
> Reviewed-on: https://chromium-review.googlesource.com/c/build/+/7214626
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Commit-Queue: Fumitoshi Ukai <ukai@google.com>

Change-Id: I081b53a22188a28f6457d57b74632a4aaf763b62
Reviewed-on: https://chromium-review.googlesource.com/c/build/+/7210118
Reviewed-by: Neri Marschik <nerima@google.com>
Commit-Queue: Neri Marschik <nerima@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>