siso: don't keep opening failure summary writer
recipe will remove failure summary file when step raised an exception,
but if siso keeps opening failure summary writer,
remove will fail with
 PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
and recipe crash (uncaught exception).

To mitigate this, append failure message when writing,
rather than keeping *os.File during the siso lifetime.

Bug: b/506222555
Change-Id: Iaa974353437a2df4dbfc488e1509061bb80eb5f1
Reviewed-on: https://chromium-review.googlesource.com/c/build/+/7805525
Reviewed-by: Philipp Wollermann <philwo@google.com>
Reviewed-by: Yuke Liao <liaoyuke@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>