Revert "siso: use digest api from remote-apis-sdks"
This reverts commit 00d29656d9ddf29090b93ab89237dddce4d15d73.

Reason for revert:

https://ci.chromium.org/ui/p/chromium/builders/ci/build-perf-linux-siso/632/overview
Error: panic: runtime error: invalid memory address or nil pointer dereference: github.com/bazelbuild/remote-apis-sdks/go/pkg/digest.NewFromProtoUnvalidated(...)

Original change's description:
> siso: use digest api from remote-apis-sdks
>
> This removes some unnecessary code from our codebase.
>
> Change-Id: Ic3c35b2bf80007e750768d6e2ddbe12a4a31cdfd
> Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4617617
> Reviewed-by: Philipp Wollermann <philwo@google.com>
> Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> Commit-Queue: Philipp Wollermann <philwo@google.com>
> Cr-Commit-Position: refs/heads/main@{#57504}

Change-Id: I85caf83ca701679729d4fbe243e47bcbfd3fea09
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/4625610
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Philipp Wollermann <philwo@google.com>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#57533}
GitOrigin-RevId: 81f1a918e814ef8bc50bf7c01bfc4f32f2bf0c23