siso: retry cas read blob
still seeing failure to read blobs
https://ci.chromium.org/ui/p/chromium/builders/build/win-build-perf-siso/268/overview

[95653/102857] CXX obj/chrome/browser/web_applications/web_applications_browser_tests/preinstalled_web_app_manager_browsertest.obj
../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /c ../../chrome/browser/web_applicatio...(too long)
remote-exec 15df775b3ca8ccca26dd3fd3fabb3ac43e4773f55d9ba250c64580139ea07908/373 failed no-fallback: failed to read blobs 8cc4dc7ef35023269baee6c52f5778e0de95c438ff906d6a5679689fb7d97958/310919 for stdout: rpc error: code = Unavailable desc = error reading from server: read tcp 10.0.34.232:53678->142.250.125.95:443: wsarecv: An existing connection was forcibly closed by the remote host.
error: 1 steps failed

We expect grpc reties, but there are some case it fails?
Explicitly retry in caller side.

Bug: b/328332495
Change-Id: I31f23dc4046c98738da7f47326621a793ec726d3
Reviewed-on: https://chromium-review.googlesource.com/c/infra/infra/+/5475090
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#64726}
GitOrigin-RevId: 0381f14599f44368b4039c36924eca2c585dd5c9