siso: fix Unavailable error handling for cartfs
If it failed to connect to cartfs, it showed
Error: could not connect to backend. If you want to build offline, pass `-o` or `--offline`
 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /tmp/.siso_vfs.sock: connect: no such file or directory"

It is confusing since `--offline` won't help here.

Show offline suggestion only if it failed to connect to RE API server.
e.g.
 Error: could not connect to backend. If you want to build offline, pass `-o` or `--offline`
 failed to check writable: upload batch: rpc error: code = Unavailable desc = batch update blobs: too many retries 10 43.3578441s: max retries exhausted: failed after 5 attempts: rpc error: code = Unavailable desc = no children to pick from

Note
 - for wrong project, it will get "code = PermissionDenied"
 - for wrong instance, it will get "Error: failed to check writable: upload batch: rpc error: code = FailedPrecondition desc = batch update blobs: rpc error: code = FailedPrecondition desc = Resource "rbe-chrome-untrusted/instances/not-exist" does not exist in this region"

Change-Id: I5d2e9e629a4851a94eeb1b275cb5fa83dc7f946c
Reviewed-on: https://chromium-review.googlesource.com/c/build/+/7978137
Reviewed-by: Philipp Wollermann <philwo@google.com>
Commit-Queue: Yuke Liao <liaoyuke@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Yuke Liao <liaoyuke@google.com>